### ISSUE TITLE
function 'fail' is not defined when missing macro detected

### ISSUE THREAD

**Issue by atul-bhouraskar** [clevercss/clevercss#15]
An undefined variable placed on a line by itself gets (correctly) considered to be an unknown macro with clevercss attempting to raise an exception fail('No macros with name "%s" is defined' % v), however 'fail' itself is undefined in the context of the recurse function in engine.py causing an unhandled exception such as:

Traceback (most recent call last):
  File "../git/clevercss/bin/ccss", line 140, in <module>
    main()
  File "../git/clevercss/bin/ccss", line 51, in main
    convert_many(args, options)
  File "../git/clevercss/bin/ccss", line 126, in convert_many
    converted = clevercss.convert(src.read(), fname=fname)
  File "/home/atul/proj/web/git/clevercss/clevercss/**init**.py", line 29, in convert
    return engine.Engine(source, fname=fname).to_css(context)
  File "/home/atul/proj/web/git/clevercss/clevercss/engine.py", line 30, in **init**
    self.rules, self._vars, self._imports = parser.parse(source)
  File "/home/atul/proj/web/git/clevercss/clevercss/engine.py", line 387, in parse
    handle_rule(i_r, i_c, i_d, macroses)
  File "/home/atul/proj/web/git/clevercss/clevercss/engine.py", line 349, in handle_rule
    recurse(macroses)
  File "/home/atul/proj/web/git/clevercss/clevercss/engine.py", line 326, in recurse
    fail('No macros with name "%s" is defined' % v)
  NameError: global name 'fail' is not defined

**Comment by encukou** [comment]
fixed by #16, thanks
